# rl-baselines3-zoo/hyperparams/mosac.yml

# MOSAC hyperparameters for different environments

PCS-RLZoo-v0:
  env_wrapper:
    - tmp.multi_objective_wrapper.MOEnergyNetWrapper:
        num_objectives: 4

  normalize: true
  num_objectives: 4
  n_envs: 1
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  batch_size: 256
  buffer_size: 1000000
  learning_rate: !!float 3e-4
  gamma: 0.99
  tau: 0.005
  train_freq: 1
  gradient_steps: 1

  policy_kwargs: "dict(net_arch=dict(pi=[64, 64], qf=[64, 64]), 
                       share_features_across_objectives=True,
                       num_objectives=4)"